import type { Metadata } from "next";
// 1. Change import from "Geist" to "Inter" (a standard Google font)
import { Inter } from "next/font/google"; 
import "./globals.css";

// 2. Initialize the font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Makerphase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 3. Apply the font class to the body */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
